### PR TITLE
Fix pull request template to satisfy Vanta

### PR DESCRIPTION
**Pull request by Mehonoshin**

### CODE REVIEW

**Review by ka8725 — APPROVED** [review]

**Comment by Mehonoshin** [comment]
@ka8725 do you have any superpower to merge this bypassing broken CI?

**Comment by ka8725** [comment]
> @ka8725 do you have any superpower to merge this bypassing broken CI?

The button is not available, let me check if I can push into master directly that gives the same effect.

**Comment by ka8725** [comment]
no :(

**Comment by ka8725** [comment]
> @ka8725 do you have any superpower to merge this bypassing broken CI?

@ayarotsky can you do that please?

**Pull request merged**
