### PR TITLE
Fix active job naming

### PR DESCRIPTION
**Pull request by urkle**
use Sidekiq's display_class to get the class name so it is mapped through ActiveJob wrappers

### CODE REVIEW

**Comment by raulpopadineti** [comment]
@urkle any way to test this out?

**Comment by urkle** [comment]
> any way to test this out?

Lots of Console testing and sifting through the code to see what Sidekiq sends over the wire:)

**Comment by raulpopadineti** [comment]
Thanks! I'll try to get to it today, or tomorrow at latest.

**Review by raulpopadineti — APPROVED** [review]

**Comment by raulpopadineti** [comment]
Looks good! 👍  

No more `sidekiq.integration.active_job_queue_adapters_sidekiq_adapter_job_wrapper.*` and metrics like that in Instrumental 😁

**Pull request merged**
